Postgres:
  user: "admin"
  password: "admin"
  host: "postgres"
  port: "5432"
  dbName: "postgres"

Redis:
  password: "admin"
  host: "redis"
  port: "6379"
  dbName: 0

System:
  service_name: "test-pkg"
  fernet_key: "fcGak6T093fEjAfd4c291IlTSVFAeLnr-e58ZcJo3Ok=" # https://8gwifi.org/CipherFunctionality
